/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#4343d5',
        'primary-container': '#5d5fef',
        'on-primary': '#ffffff',
        'primary-fixed': '#e1e0ff',
        'primary-fixed-dim': '#c1c1ff',
        'on-primary-fixed': '#07006c',
        'on-primary-fixed-variant': '#2e2bc2',
        'surface-tint': '#4849da',
        secondary: '#855300',
        'secondary-container': '#fea619',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#684000',
        'secondary-fixed': '#ffddb8',
        'secondary-fixed-dim': '#ffb95f',
        tertiary: '#555a64',
        background: '#f8f9ff',
        'on-background': '#121c28',
        surface: '#f8f9ff',
        'on-surface': '#121c28',
        'on-surface-variant': '#464555',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eef4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dfe9fa',
        'surface-container-highest': '#d9e3f4',
        'surface-variant': '#d9e3f4',
        outline: '#767586',
        'outline-variant': '#c7c4d7',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'inverse-surface': '#27313e',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#c1c1ff',
      },
      fontFamily: {
        sans: ['"Inter Variable"', 'Inter', 'system-ui', 'sans-serif'],
        display: ['"Public Sans Variable"', 'Public Sans', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        caption: ['12px', { lineHeight: '16px', fontWeight: '600' }],
        label: ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        body: ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        title: ['24px', { lineHeight: '32px', fontWeight: '600' }],
        headline: ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        md: '16px',
        base: '8px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        gutter: '24px',
      },
      boxShadow: {
        lift: '0 4px 20px rgba(93, 95, 239, 0.08)',
      },
      transitionDuration: {
        DEFAULT: '200ms',
      },
    },
  },
  plugins: [],
};
